version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

      - jwt.secret=${JWT_SECRET}
      - jwt.jwtExpirationMs=${JWT_EXPIRATION_MS}
      - jwt.refreshTokenDurationMs=${JWT_REFRESH_MS}

      - spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}

    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db-data:
